name: container-worflow

on: [push]

jobs:
  node-container-jobs:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Print Node Version
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\", \"address\": \" qewrt\"}'"
        
     