name: matrix-workflow

on: push

jobs:
  Node-version-Job:
    strategy:
      matrix:
        node_version: [6, 12, 14]
      fail-fast: true
    runs-on: ubuntu-latest
    steps: 
      - name: Node Version before setup node action
        run: node -v 
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Node Version after setup node action
        run: node -v 


  
