name: Actions-WorkFlow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before Checkout
        id: List-Pre
        run: |
          pwd
          ls -la
      - name: Checkout-Steps
        id: Checkout
        uses: actions/checkout@v3
      - name: List Files After Checkout
        id: List-Post
        run: |
          pwd
          ls -la
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with: 
          who-to-greet: "John"
      - name: Capture TimeStamp of greet
        run: echo "${{ steps.greet.outputs.time }}"
